
<div class="text-center"><h2> Anatomy of an error message: the Traceback </h2></div><hr />
<p>
    The previous pair of lines indicated to us that 
    the error occurred during the execution of 
    the <code>sum_pairs</code> function. Moving 
    to the pair of lines above it tells us where the 
    <code>sum_pairs</code> function was called 
    to give us some more context as to the how the 
    error occurred.
</p>
<ul>
    <li>
        The first line tells us that the <code>
        sum_pairs</code> function was called 
        in <code>sum_pairs.py</code>, on line 
        23, in the <code>main</code> function. 
        Additionally, we see that it's called 
        with the parameter <code>[1, 2, 3, 4]</code>.
    </li>
    <li>
        The second line shows us the contents
        of the line of code in question. 
    </li>
</ul>